[package]
name = "nitro_gui"
version = "0.31.0"
description = "The command-line interface for Nitrolaunch"
keywords = ["minecraft", "launcher", "game", "mc", "cli"]
categories = ["games", "command-line-utilities"]
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[package.metadata.packager]
product_name = "Nitrolaunch"
version = "0.31.0"
identifier = "org.nitrolaunch.gui"
description = "Nitrolaunch GUI"
icons = [
  "assets/icon_1024x1024.png",
  "assets/icon.ico",
  "assets/icon.icns"
]

[[package.metadata.packager.binaries]]
path = "nitro_gui"
main = true

[package.metadata.packager.linux]
generate_desktop_entry = true

[package.metadata.packager.deb]
desktop_template = "assets/Nitrolaunch.desktop"

[features]
devtools = ["freya/devtools"]
profiler = ["freya/performance"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
freya = { workspace = true }
freya-core = { workspace = true }
html_parser = { workspace = true }
nitrolaunch = { workspace = true }
open = { workspace = true }
reqwest = { workspace = true }
rfd = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "fs"] }

[target.'cfg(target_os = "linux")'.dependencies]
which = { workspace = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
static_vcruntime = "2.0"

[[bin]]
name = "nitro_gui"
path = "src/main.rs"
